:star: erlang 버전 기록, USE_GLOBAL_ELIXIR 환경 변수 검사
- elixir가 어디 혼자 돌아다녀?
  - 빠진 erlang 버전 기록
- asdf 기본 프로그램만 깔렸을때를 고려한 플러그인 설치
- USE_GLOBAL_ELIXIR=true 세팅하면 asdf install을 건너띈다
  - elixir가 준비된 ci, docker 사용시 세팅할 예정

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -8,13 +8,19 @@ set -e
 
 cd "$(dirname "$0")/.."
 
-if ! command -v asdf > /dev/null; then
-    echo "FAILED: 'asdf' is not installed"
-    exit 1
-fi
+if [[ "${USE_GLOBAL_ELIXIR}" = true ]]; then
+    echo "SKIP: use global elixir instead of asdf elixir"
+else
+    if ! command -v asdf > /dev/null; then
+        echo "FAILED: 'asdf' is not installed"
+        exit 1
+    fi
 
-# install all the tools defined in a '.tool-versions'
-asdf install
+    asdf plugin add erlang || true
+    asdf plugin add elixir || true
+    # install all the tools defined in a '.tool-versions'
+    asdf install
+fi
 
 mix local.hex --force
 mix local.rebar --force
